import type { Metadata } from "next";
<<<<<<< HEAD
import { ConfigProvider } from "antd";
=======
import { Inter } from "next/font/google";
>>>>>>> 013a2ff
import "./globals.css";
import { ConfigProvider, App as AntApp } from "antd";

<<<<<<< HEAD
export const metadata: Metadata = {
  title: "Ant Design App",
  description: "A Next.js application with Ant Design",
=======
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 013a2ff
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="zh-CN">
      <body>
        <ConfigProvider
          theme={{
            token: {
              fontFamily:
                "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            },
          }}
        >
          {children}
=======
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "white" }}>
        <ConfigProvider>
          <AntApp>{children}</AntApp>
>>>>>>> 013a2ff
        </ConfigProvider>
      </body>
    </html>
  );
}
